name: Print Pusher Name

on:
  push:
    branches:
      - '**' # This will trigger on pushes to any branch.

jobs:
  print-pusher:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print pusher's username
        run: |
            echo "This push was triggered by: '${{ toJson(github.event) }}'"

      - name: Print PR URL
        run: |
            echo "Pull Request URL: ${{ github.event.pull_request.html_url }}"     
          