name: Trigger Odigos Enterprise Workflow

on:
  push:
    branches:
      - '**'

jobs:
  trigger-odigos-enterprise:
    runs-on: ubuntu-latest
    steps:  
      - name: Fetch Associated PR
        id: fetch_pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Define variables
          REPO_OWNER="AvihuHenya"
          REPO_NAME="github-workflow"
          COMMIT_SHA="${{ github.sha }}" # Commit SHA from the push event

          # Query GitHub API for PRs linked to the commit
          RESPONSE=$(curl -s \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.groot-preview+json" \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/commits/$COMMIT_SHA/pulls")

          echo "API Response: $RESPONSE" # Debug response

          # Extract PR URL
          PR_URL=$(echo "$RESPONSE" | jq -r '.[0].html_url')

          if [ "$PR_URL" != "null" ]; then
            echo "PR_URL=$PR_URL" >> $GITHUB_ENV
            echo "Pull Request URL: $PR_URL"
          else
            echo "No PR found for commit: $COMMIT_SHA"
          fi


      - name: Trigger workflow in another repository
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.REMOTE_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/AvihuHenya/remote-repo/dispatches \
          -d '{"event_type": "enterprise-dependencies-update", "client_payload": {"pr_creator": "${{ github.event.pusher.name }}", "source_pr_url": "${{ env.PR_URL }}" }}'
          