name: Trigger Odigos Enterprise Workflow

on:
  push:
    branches:
      - '**'
jobs:
  trigger-odigos-enterprise:
    runs-on: ubuntu-latest
    steps:    
      - name: Trigger workflow in another repository
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.REMOTE_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/AvihuHenya/remote-repo/dispatches \
          -d '{"event_type": "enterprise-dependencies-update", "client_payload": {"pr_creator": "${{ github.event.pull_request.user.login }}"}}'