name: Trigger Odigos Enterprise Workflow

on:
  pull_request:
    types:
      - opened
      - reopened
      - closed
jobs:
  trigger-odigos-enterprise:
    runs-on: ubuntu-latest
    steps:    
      - name: Trigger process PR in Odigos Enterprise
        run: |
          ehco "pr_creator": "${{ github.event.pull_request.user.login }}""
