name: Trigger Odigos Enterprise Workflow

on:
  push:
    branches:
      - '**'
jobs:
  trigger-odigos-enterprise:
    runs-on: ubuntu-latest
    steps:    
      - name: Trigger process PR in Odigos Enterprise
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/AvihuHenya/remote-repo/dispatches \
          -d '{"event_type": "enterprise-dependencies-update", "client_payload": {"pr_creator": "${{ github.event.pull_request.user.login }}"}}'
